name: Deploy Backend to Render

on:
  push:
    branches:
      - Nirav#05-new_apis_added

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
