name: Build & Deploy Backend to Render

on:
  push:
    branches:
      - Nirav#05-new_apis_added

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # Step 3: Install backend dependencies
      - name: Install dependencies
        run: npm ci

      # Optional: Run tests or build steps if needed
      # - name: Run tests
      #   run: npm test

      # Step 4: Trigger deployment on Render
      - name: Trigger Render Deployment
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
